# Generated by Django 5.0.4 on 2024-04-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='MamarBank', max_length=10, null=True)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='Bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='accounts.bank'),
        ),
    ]
