# Generated by Django 5.0.4 on 2024-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bank_userbankaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
