# Generated by Django 5.0.4 on 2024-04-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
