# Generated by Django 5.0.4 on 2024-04-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bank_balance'),
        ('transactions', '0003_delete_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_money', to='accounts.userbankaccount'),
        ),
    ]
