# Generated by Django 5.0.4 on 2024-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_sender_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
